version: '3'
services:

  mongodb:
    image: mongo:latest
    restart: always
    container_name: hra__mongodb
    hostname: hra__mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGODB_DATABASE: orders
    ports:
      - "27017:27017"
    volumes:
      - ./docker/storage/mongo:/data/db

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./monitoring/prometheus_docker.yml.yml:/etc/prometheus/prometheus.yml:ro

  node_exporter:
    container_name: node_exporter_container
    restart: always
    image: prom/node-exporter
    ports:
      - '9101:9100'

  jaeger:
    container_name: hra__jaeger
    hostname: hra__jaeger
    restart: always
    image: jaegertracing/all-in-one:1.21
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.143.0/24