version: '3'
services:

  mongodb:
    image: mongo:latest
    restart: always
    container_name: hra__mongodb
    hostname: hra__mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGODB_DATABASE: orders
    ports:
      - "27017:27017"
    volumes:
      - ./docker/storage/mongo:/data/db

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.143.0/24